# Базовые параметры настройки конфигурации проекта
dbname: postgres # В классе менять не надо
user: postgres # Замените на свой логин от БД в классе
password: qwerty # Замените на свой пароль от БД в классе
host: localhost # Замените на 192.168.0.48 в классе
port: 5433
dbtableprefix: "public."  # Замените на свой логин от